# Generated by Django 5.2.15 on 2026-06-09 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название игры')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='URL-слаг')),
                ('content', models.TextField(verbose_name='Содержимое рецензии')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
