# Generated by Django 5.2.15 on 2026-06-16 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_review_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author', '-created_at'], name='review_author_date_idx'),
        ),
    ]
