# Generated by Django 5.2.15 on 2026-08-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_created_at_alter_review_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг'),
        ),
    ]
