# Generated by Django 5.2.15 on 2026-08-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/covers/%Y/%m/', verbose_name='Обложка'),
        ),
    ]
